### PR TITLE
Fix typo with backwards compatibility for HEALTH_CHECK_PATH

### PR DESCRIPTION
**Pull request by vitorarins**

### CODE REVIEW

**Comment by JorritSalverda** [comment]
An unfortunate typo. Indeed to fix it in a backwards compatible way since we inject the HEALT_CHECK_PATH in a lot of kubernetes manifests.

**Comment by JorritSalverda** [comment]
Make sure to test this with a couple of applications that use the old envvar to see if it's drop in compatible and we can actually merge it without any negative side effects.

**Comment by JorritSalverda** [comment]
Can this be closed?

**Comment by vitorarins** [comment]
Well I remember testing this with a couple of deployments, but it doesn't look so necessary as we are mostly setting this through automation. So I guess we can close this.

**Pull request closed without merging**
